apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: frontend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: frontend
  mimReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuUtilization}} # usually 75